In [1]:
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report

In [2]:
true_labels = [2, 0, 0, 2, 4, 4, 1, 0, 3, 3, 3] 
pred_labels = [2, 1, 0, 2, 4, 3, 1, 0, 1, 3, 3]

In [3]:
confusion_mat = confusion_matrix(true_labels, pred_labels)
print(confusion_mat)

[[2 1 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 1 0 2 0]
 [0 0 0 1 1]]
